# Generated by Django 5.2.1 on 2025-06-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula'),
        ),
    ]
