# Generated by Django 5.2.1 on 2025-05-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='empresa')),
                ('cnpj', models.CharField(blank=True, max_length=17, null=True, verbose_name='cnpj')),
                ('representative', models.CharField(blank=True, max_length=200, null=True, verbose_name='representante')),
                ('phone', models.CharField(max_length=15, verbose_name='contato')),
                ('rg', models.CharField(blank=True, max_length=13, null=True, verbose_name='rg')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='cpf')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
