# Generated by Django 5.2.1 on 2025-05-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='approved_by',
        ),
    ]
