# Generated by Django 5.2.1 on 2025-05-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('number', models.CharField(max_length=50, verbose_name='numero')),
                ('modality', models.CharField(max_length=100, verbose_name='modalidade')),
                ('year', models.PositiveIntegerField(verbose_name='ano')),
                ('approval_date', models.DateField(verbose_name='data da Homologação')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='valor')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
