# Generated by Django 5.2.1 on 2025-05-25 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biddings', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('target', models.TextField(verbose_name='Objeto')),
                ('assignature_data', models.DateField(verbose_name='Data da assinatura')),
                ('start_date', models.DateField(verbose_name='Data inicial')),
                ('end_date', models.DateField(verbose_name='Data final')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor total')),
                ('bidding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biddings.bidding')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('type', models.CharField(choices=[('prorrogacao', 'Prorrogação'), ('financeiro', 'Financeiro'), ('misto', 'Misto')], max_length=20, verbose_name='Tipo')),
                ('motivation', models.TextField(verbose_name='Motivação')),
                ('new_end_date', models.DateField(blank=True, null=True, verbose_name='Nova data final')),
                ('new_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor novo')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especification', models.TextField(verbose_name='Especificação')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_new', to='contracts.amendment')),
            ],
        ),
        migrations.CreateModel(
            name='ItemContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especification', models.TextField(verbose_name='Especificação')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidade')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço unitário')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contract')),
            ],
        ),
    ]
