# Generated by Django 5.2.1 on 2025-05-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biddings', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('number', models.CharField(max_length=50, verbose_name='número')),
                ('target', models.TextField(verbose_name='objeto')),
                ('assignature_data', models.DateField(verbose_name='data da assinatura')),
                ('start_date', models.DateField(verbose_name='data inicial')),
                ('end_date', models.DateField(verbose_name='data final')),
                ('bidding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biddings.bidding')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='especificação')),
                ('unit', models.CharField(max_length=20, verbose_name='unidade')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contracts.contract')),
            ],
        ),
    ]
