# Generated by Django 5.2.1 on 2025-05-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('number',), 'verbose_name_plural': 'Contratos'},
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='inspector_sustitute',
            new_name='inspector_substitute',
        ),
    ]
