# Generated by Django 5.2.1 on 2025-05-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcontract',
            name='consumed_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade consumida'),
        ),
    ]
