# Generated by Django 5.2.1 on 2025-05-29 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcontract',
            name='fiscal',
        ),
        migrations.RemoveField(
            model_name='itemcontract',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='itemcontract',
            name='suplente_fiscal',
        ),
        migrations.RemoveField(
            model_name='itemcontract',
            name='suplente_gestor',
        ),
    ]
