# Generated by Django 5.2.1 on 2025-05-30 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_itemcontract_fiscal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='inspector_substitute',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='manager_substitute',
        ),
        migrations.CreateModel(
            name='ContractUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Gestor'), ('manager_substitute', 'Suplente do Gestor'), ('inspector', 'Fiscal'), ('inspector_substitute', 'Suplente do Fiscal')], max_length=30)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
